=== eronepius/AUMCACT/xml/data.dtd
<!ELEMENT employee (id,first_name,last_name,email,gender,portfolio,salary,SkillSet)>
<!ELEMENT employees (employee*)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT portfolio (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT SkillSet (#PCDATA)>

=== eronepius/AUMCACT/xml/data.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE employees SYSTEM "data.dtd">  
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="data.xsd">
  <employee>
    <id>1</id>
    <first_name>Sisile</first_name>
    <last_name>Ballsdon</last_name>
    <email>sballsdon0@google.it</email>
    <gender>Female</gender>
    <portfolio>VCG</portfolio>
    <salary>4066104</salary>
    <SkillSet>Program Management Scrum Alliance</SkillSet>
  </employee>
  <employee>
    <id>2</id>
    <first_name>Georas</first_name>
    <last_name>Olech</last_name>
    <email>golech1@1und1.de</email>
    <gender>Female</gender>
    <portfolio>AI and D</portfolio>
    <salary>3647072</salary>
    <SkillSet>Python Java SQL</SkillSet>
  </employee>
  <employee>
    <id>3</id>
    <first_name>Abbi</first_name>
    <last_name>Woollett</last_name>
    <email>awoollett2@themeforest.net</email>
    <gender>Male</gender>
    <portfolio>MEDIA</portfolio>
    <salary>3030599</salary>
    <SkillSet>Database Mangement SQL NoSQL Mongo</SkillSet>
  </employee>
  <employee>
    <id>4</id>
    <first_name>Eadith</first_name>
    <last_name>Iacapucci</last_name>
    <email>eiacapucci3@va.gov</email>
    <gender>Male</gender>
    <portfolio>VIPS</portfolio>
    <salary>3548529</salary>
    <SkillSet>Machine Learning Data Analysis</SkillSet>
  </employee>
  <employee>
    <id>5</id>
    <first_name>Isadore</first_name>
    <last_name>Jancy</last_name>
    <email>ijancy4@bandcamp.com</email>
    <gender>Female</gender>
    <portfolio>DWP</portfolio>
    <salary>1284113</salary>
    <SkillSet>Program Management Scrum Alliance</SkillSet>
  </employee>
  <employee>
    <id>6</id>
    <first_name>Osbert</first_name>
    <last_name>Choules</last_name>
    <email>ochoules5@msn.com</email>
    <gender>Female</gender>
    <portfolio>AI and D</portfolio>
    <salary>1746553</salary>
    <SkillSet>Business Analysis</SkillSet>
  </employee>
  <employee>
    <id>7</id>
    <first_name>Clarie</first_name>
    <last_name>Sturdy</last_name>
    <email>csturdy6@sun.com</email>
    <gender>Bigender</gender>
    <portfolio>VCG</portfolio>
    <salary>2612854</salary>
    <SkillSet>Deep Learning</SkillSet>
  </employee>
  <employee>
    <id>8</id>
    <first_name>Ashlin</first_name>
    <last_name>Hardistry</last_name>
    <email>ahardistry7@mozilla.org</email>
    <gender>Female</gender>
    <portfolio>VIPS</portfolio>
    <salary>2983868</salary>
    <SkillSet>Program Management Scrum Alliance</SkillSet>
  </employee>
  <employee>
    <id>9</id>
    <first_name>Jaime</first_name>
    <last_name>Mintram</last_name>
    <email>jmintram8@ustream.tv</email>
    <gender>Female</gender>
    <portfolio>VBG</portfolio>
    <salary>4274853</salary>
    <SkillSet>DevOps Kubernetes</SkillSet>
  </employee>
  <employee>
    <id>10</id>
    <first_name>Horacio</first_name>
    <last_name>Scourfield</last_name>
    <email>hscourfield9@nydailynews.com</email>
    <gender>Male</gender>
    <portfolio>VCG</portfolio>
    <salary>4013109</salary>
    <SkillSet>Python Java SQL</SkillSet>
  </employee>
  <employee>
    <id>11</id>
    <first_name>Jim</first_name>
    <last_name>Blatcher</last_name>
    <email>jblatchera@blog.com</email>
    <gender>Polygender</gender>
    <portfolio>VBG</portfolio>
    <salary>1078308</salary>
    <SkillSet>Deep Learning</SkillSet>
  </employee>
  <employee>
    <id>12</id>
    <first_name>Fedora</first_name>
    <last_name>Saing</last_name>
    <email>fsaingb@bing.com</email>
    <gender>Female</gender>
    <portfolio>VBG</portfolio>
    <salary>4201397</salary>
    <SkillSet>Jira Git Jenkins Operations</SkillSet>
  </employee>
  <employee>
    <id>13</id>
    <first_name>Freddy</first_name>
    <last_name>Duffet</last_name>
    <email>fduffetc@boston.com</email>
    <gender>Male</gender>
    <portfolio>DWP</portfolio>
    <salary>3161008</salary>
    <SkillSet>Machine Learning Data Analysis</SkillSet>
  </employee>
  <employee>
    <id>14</id>
    <first_name>Raynell</first_name>
    <last_name>Semper</last_name>
    <email>rsemperd@princeton.edu</email>
    <gender>Female</gender>
    <portfolio>VCG</portfolio>
    <salary>1412951</salary>
    <SkillSet>Database Mangement SQL NoSQL Mongo</SkillSet>
  </employee>
  <employee>
    <id>15</id>
    <first_name>Melisent</first_name>
    <last_name>Yapp</last_name>
    <email>myappe@digg.com</email>
    <gender>Female</gender>
    <portfolio>VBG</portfolio>
    <salary>2773491</salary>
    <SkillSet>Deep Learning</SkillSet>
  </employee>
  <employee>
    <id>16</id>
    <first_name>Deana</first_name>
    <last_name>Howle</last_name>
    <email>dhowlef@webnode.com</email>
    <gender>Female</gender>
    <portfolio>AI and D</portfolio>
    <salary>1424739</salary>
    <SkillSet>Deep Learning</SkillSet>
  </employee>
  <employee>
    <id>17</id>
    <first_name>Carmine</first_name>
    <last_name>Kleinstub</last_name>
    <email>ckleinstubg@comsenz.com</email>
    <gender>Male</gender>
    <portfolio>VCG</portfolio>
    <salary>2477717</salary>
    <SkillSet>Machine Learning Data Analysis</SkillSet>
  </employee>
  <employee>
    <id>18</id>
    <first_name>Alice</first_name>
    <last_name>Mackelworth</last_name>
    <email>amackelworthh@w3.org</email>
    <gender>Female</gender>
    <portfolio>MEDIA</portfolio>
    <salary>1851896</salary>
    <SkillSet>Jira Git Jenkins Operations</SkillSet>
  </employee>
  <employee>
    <id>19</id>
    <first_name>Di</first_name>
    <last_name>Ajean</last_name>
    <email>dajeani@elegantthemes.com</email>
    <gender>Female</gender>
    <portfolio>VCG</portfolio>
    <salary>4535170</salary>
    <SkillSet>Machine Learning Data Analysis</SkillSet>
  </employee>
  <employee>
    <id>20</id>
    <first_name>Reggi</first_name>
    <last_name>McGrouther</last_name>
    <email>rmcgroutherj@admin.ch</email>
    <gender>Genderfluid</gender>
    <portfolio>AI and D</portfolio>
    <salary>4243139</salary>
    <SkillSet>Program Management Scrum Alliance</SkillSet>
  </employee>
  <employee>
    <id>21</id>
    <first_name>Ferris</first_name>
    <last_name>Mouatt</last_name>
    <email>fmouattk@123-reg.co.uk</email>
    <gender>Male</gender>
    <portfolio>DWP</portfolio>
    <salary>2477982</salary>
    <SkillSet>Program Management Scrum Alliance</SkillSet>
  </employee>
  <employee>
    <id>22</id>
    <first_name>Trixy</first_name>
    <last_name>MacCroary</last_name>
    <email>tmaccroaryl@goo.gl</email>
    <gender>Male</gender>
    <portfolio>AI and D</portfolio>
    <salary>3964813</salary>
    <SkillSet>Scala Data Engineering</SkillSet>
  </employee>
  <employee>
    <id>23</id>
    <first_name>Elsy</first_name>
    <last_name>Rodgers</last_name>
    <email>erodgersm@cmu.edu</email>
    <gender>Female</gender>
    <portfolio>VIPS</portfolio>
    <salary>1732293</salary>
    <SkillSet>Scala Data Engineering</SkillSet>
  </employee>
  <employee>
    <id>24</id>
    <first_name>Gregorius</first_name>
    <last_name>Klimecki</last_name>
    <email>gklimeckin@army.mil</email>
    <gender>Male</gender>
    <portfolio>MEDIA</portfolio>
    <salary>1274372</salary>
    <SkillSet>Scala Data Engineering</SkillSet>
  </employee>
  <employee>
    <id>25</id>
    <first_name>Nataline</first_name>
    <last_name>Gellately</last_name>
    <email>ngellatelyo@discuz.net</email>
    <gender>Female</gender>
    <portfolio>VBG</portfolio>
    <salary>3974705</salary>
    <SkillSet>Deep Learning</SkillSet>
  </employee>
  <employee>
    <id>26</id>
    <first_name>Mabelle</first_name>
    <last_name>Heining</last_name>
    <email>mheiningp@bizjournals.com</email>
    <gender>Male</gender>
    <portfolio>MEDIA</portfolio>
    <salary>1479783</salary>
    <SkillSet>Scala Data Engineering</SkillSet>
  </employee>
  <employee>
    <id>27</id>
    <first_name>Karlis</first_name>
    <last_name>Banbridge</last_name>
    <email>kbanbridgeq@redcross.org</email>
    <gender>Female</gender>
    <portfolio>VIPS</portfolio>
    <salary>1227573</salary>
    <SkillSet>Business Analysis</SkillSet>
  </employee>
  <employee>
    <id>28</id>
    <first_name>Sukey</first_name>
    <last_name>Bris</last_name>
    <email>sbrisr@jimdo.com</email>
    <gender>Male</gender>
    <portfolio>DWP</portfolio>
    <salary>568861</salary>
    <SkillSet>Deep Learning</SkillSet>
  </employee>
  <employee>
    <id>29</id>
    <first_name>Odelle</first_name>
    <last_name>Ayers</last_name>
    <email>oayerss@acquirethisname.com</email>
    <gender>Male</gender>
    <portfolio>VCG</portfolio>
    <salary>1828145</salary>
    <SkillSet>Business Analysis</SkillSet>
  </employee>
  <employee>
    <id>30</id>
    <first_name>Neilla</first_name>
    <last_name>Manntschke</last_name>
    <email>nmanntschket@bloomberg.com</email>
    <gender>Female</gender>
    <portfolio>VCG</portfolio>
    <salary>561019</salary>
    <SkillSet>Scala Data Engineering</SkillSet>
  </employee>
  <employee>
    <id>31</id>
    <first_name>Haley</first_name>
    <last_name>Vevers</last_name>
    <email>hveversu@goo.gl</email>
    <gender>Male</gender>
    <portfolio>VIPS</portfolio>
    <salary>4002350</salary>
    <SkillSet>Jira Git Jenkins Operations</SkillSet>
  </employee>
  <employee>
    <id>32</id>
    <first_name>Justen</first_name>
    <last_name>Duker</last_name>
    <email>jdukerv@google.it</email>
    <gender>Male</gender>
    <portfolio>VCG</portfolio>
    <salary>4588685</salary>
    <SkillSet>DevOps Kubernetes</SkillSet>
  </employee>
  <employee>
    <id>33</id>
    <first_name>Rutger</first_name>
    <last_name>Casswell</last_name>
    <email>rcasswellw@dropbox.com</email>
